"use client";
// import type { Metadata } from "next";
import { useEffect, useState } from "react";
import Navbar from "./sections/Navbar";
import Footer from './sections/Footer'
// These styles apply to every route in the application
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  useEffect(() => {
    const prefersDarkMode = window.matchMedia("(prefers-color-scheme: dark)");
    const localStorageTheme = localStorage.getItem("theme");

    const setDarkMode = (shouldAddDarkClass: boolean) => {
      const htmlElement = document.documentElement;
      if (shouldAddDarkClass) {
        htmlElement.classList.add("dark");
      } else {
        htmlElement.classList.remove("dark");
      }
    };

    if (
      localStorageTheme === "dark" ||
      (!localStorageTheme && prefersDarkMode.matches)
    ) {
      setDarkMode(true);
    } else {
      setDarkMode(false);
    }
  }, []);
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}